[build]
command = "deno run --allow-read --allow-write --allow-env https://netlify-changelog-redirects.netlify.app/1.1.0/cli.ts --changelog CHANGELOG.md --target src/_redirects"
publish = "src"

[[headers]]
for = "/*.js"
[headers.values]
Content-Type = "application/javascript; charset=utf-8"

[[headers]]
for = "/*.ts"
[headers.values]
Content-Type = "application/typescript; charset=utf-8"
